apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-sample-app
  labels:
    app: python-app # label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app # label
  template:
    metadata:
      labels:
        app: python-app # label
    spec:
      containers:
      - name: python-sample # container name
        image: python-app:v1
        ports:
        - containerPort: 8000 # port on which app is running
